name: talky_aplication_2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.0
  email_auth: ^2.0.0
  pinput: ^5.0.0
  cloud_firestore: ^5.4.0
  provider: ^6.1.2
  email_otp: ^3.0.2
  firebase_storage: ^12.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  timeago: ^3.7.0
  google_sign_in: ^6.2.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.1
  file_picker: ^8.1.2
  record: ^5.1.2
  dio: ^5.7.0
  http: ^1.2.2
  path_provider: ^2.1.4
  open_file: ^3.5.8
  path: ^1.9.0
  flutter_pdfview: ^1.3.3
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^27.1.52
  file_downloader_flutter: ^0.0.5
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  modal_bottom_sheet: ^3.0.0

dependency_overrides:
  intl: 0.18.1
  file: ^6.1.0
  pub_updater: ^0.3.0
  http: ^1.2.2
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dart_code_metrics: 5.7.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  # https://flutter.dev/to/resolution-aware-images

  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/to/font-from-package
